name = "Star Techology"
author = "trulyno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4de2e6afd27b6eb4f451d490354460a765acdb338bcbfa9bc20f272a7490b189"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
