name = "Star Techology"
author = "trulyno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84576a4853f552f4757dd39165f03786f95736bdcd6239a69682b203d490eb91"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
