name = "Star Techology"
author = "trulyno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cd31323bb5e5ece2650d5316b13689512334ac4c3dad6a4cf47b45d27879ff9"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
